(function(root,factory){"use strict";var api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.EngineDemoSearch=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){"use strict";
var MULTI_FILTERS=["source","kind","category","language"];
var REFUSAL="The bundled demo sources do not answer this query. Switch to Live Mode to search the full index.";
function tokens(value){return String(value||"").toLowerCase().match(/[a-z0-9]+/g)||[];}
function includesAny(selected,values){if(!selected||!selected.length)return true;return selected.some(function(item){return values.indexOf(String(item).toLowerCase())>=0;});}
function matchesFilters(doc,filters){filters=filters||{};for(var i=0;i<MULTI_FILTERS.length;i+=1){var key=MULTI_FILTERS[i];var values=key==="category"?doc.categories||[]:[doc[key]==null?"":String(doc[key])];values=values.map(function(value){return String(value).toLowerCase();});if(!includesAny(filters[key],values))return false;}if(filters.has_code==="true"&&!doc.has_code)return false;if(filters.has_equations==="true"&&!doc.has_equations)return false;return true;}
function countMatches(haystack,queryTerms){var values=tokens(haystack);return queryTerms.reduce(function(count,term){return count+values.filter(function(value){return value===term;}).length;},0);}
function scoreDocument(doc,query,queryTerms){if(!queryTerms.length)return 1;var lowerQuery=query.toLowerCase();var title=String(doc.title||"").toLowerCase();var abstract=String(doc.abstract||"").toLowerCase();var tags=(doc.tags||[]).concat(doc.categories||[]).join(" ");var score=countMatches(title,queryTerms)*8+countMatches(abstract,queryTerms)*3+countMatches(tags,queryTerms)*2+countMatches(doc.source+" "+doc.kind,queryTerms);if(title.indexOf(lowerQuery)>=0)score+=12;else if(abstract.indexOf(lowerQuery)>=0)score+=5;return score;}
function facet(rows,key){var counts=Object.create(null);rows.forEach(function(row){var values=key==="category"?row.doc.categories||[]:[row.doc[key]];values.forEach(function(value){if(value==null||value==="")return;counts[value]=(counts[value]||0)+1;});});return Object.keys(counts).sort().map(function(value){return {value:value,count:counts[value]};});}
function search(corpus,request){request=request||{};var query=String(request.q||"").trim();var queryTerms=tokens(query);var page=Math.max(1,Number(request.page)||1);var perPage=Math.max(1,Math.min(100,Number(request.per_page)||20));var rows=corpus.filter(function(doc){return matchesFilters(doc,request.filters);}).map(function(doc){return {doc:doc,score:scoreDocument(doc,query,queryTerms)};}).filter(function(row){return !queryTerms.length||row.score>0;}).sort(function(a,b){return b.score-a.score||a.doc.id.localeCompare(b.doc.id);});var start=(page-1)*perPage;return {query:query,mode:"demo-lexical",total:rows.length,page:page,per_page:perPage,took_ms:0,facets:{source:facet(rows,"source"),kind:facet(rows,"kind"),category:facet(rows,"category"),language:facet(rows,"language"),has_code:[{value:true,count:rows.filter(function(row){return row.doc.has_code;}).length}],has_equations:[{value:true,count:rows.filter(function(row){return row.doc.has_equations;}).length}]},hits:rows.slice(start,start+perPage).map(function(row){return {score:row.score,highlights:row.doc.abstract?[row.doc.abstract]:[],document:row.doc};})};}
function sentences(text){return String(text||"").replace(/\s+/g," ").split(/(?<=[.!?])\s+/).filter(function(sentence){return sentence.length>20;});}
function summarize(corpus,query,documentIds){var queryTerms=tokens(query);var byId=Object.create(null);corpus.forEach(function(doc){byId[doc.id]=doc;});var chosen=[];(documentIds||[]).forEach(function(id){var doc=byId[id];if(!doc)return;sentences(doc.abstract||doc.body).forEach(function(sentence){var overlap=countMatches(sentence,queryTerms);if(overlap>0)chosen.push({doc:doc,sentence:sentence,overlap:overlap});});});chosen.sort(function(a,b){return b.overlap-a.overlap||a.doc.id.localeCompare(b.doc.id);});chosen=chosen.slice(0,4);if(!chosen.length)return {query:query,answer:REFUSAL,generator:"demo-extractive",citations:[]};var citations=[];var numberById=Object.create(null);var answer=chosen.map(function(item){if(!numberById[item.doc.id]){numberById[item.doc.id]=citations.length+1;citations.push({n:citations.length+1,id:item.doc.id,title:item.doc.title,url:item.doc.url||item.doc.pdf_url,source:item.doc.source});}return item.sentence+" ["+numberById[item.doc.id]+"]";}).join(" ");return {query:query,answer:answer,generator:"demo-extractive",citations:citations};}
function createProvider(corpus){return {health:function(){return Promise.resolve({ready:true,provider:"demo",backend:"bundled",retrieval:"demo-lexical",vector_search:false,document_count:corpus.length,label:"Demo · "+corpus.length+" bundled documents"});},search:function(request){return Promise.resolve(search(corpus,request));},summarize:function(request){return Promise.resolve(summarize(corpus,request.query,request.documentIds));},sources:function(){var names=Array.from(new Set(corpus.map(function(doc){return doc.source;}))).sort();return Promise.resolve({sources:names.map(function(name){return {name:name,display_name:name+" (demo)"};})});}};}
return {createProvider:createProvider,search:search,summarize:summarize,tokens:tokens};
});
